Cleanup
  - use associative arrays keyed on module name
    - this means we don't need to use eval and
      can delete or check by key
    - moved to top of file so easier to change

  - i18n strings

diff --git a/genalyze b/genalyze
--- a/genalyze
+++ b/genalyze
@@ -1,114 +1,149 @@
 #!/bin/bash
-#genalyze.sh
+#genalyze
 #this script gathers some data about your system and pastes them online 
 #for other people, so that they can help you with your problem
 # this script is perfectly safe if run as normal user, you may need to be root
 # to emerge wgetpaste though 
 
+PATH="$PATH:/usr/sbin:/sbin" #this is needed for utils like lspci
 
-PATH="${PATH}:/usr/sbin:/sbin" #this is needed for utils like lspci
+out_tmp="/tmp/genalyze_output_$(date +%Y%m%d_%H%M%S).txt" #the temporary file to be pasted online
+    
+#######################################<<MODULE ARRAYS>>################################
+# we keep class arrays, keyed by module_identifier, which hold the description
+# each array is used for the functions named below by removing _array from the name
+declare -A analyze_array analyze_opt_array query_array
 
+#format: class_array=([module_identifier_1]=$"module description" [module_identifier_2]=$".." ..)
+# module_identifier: short, no whitespace (used for referencing from command-line)
+# module description: capitalised, and no abbreviations please, should be understandable for everyone
+# $".." as in: $"user displayed text" allows us to localize strings when we choose
+# NB: you must also place the command (or query string) in the data array below
 
-out_tmp="/tmp/genalyze_output_$(date +%d%m%y_%H%M%S).txt" #the temporary file to be pasted online
-interactive=1
-readonly=0
+# standard modules run by analyze()
+analyze_array=(
+    [rc_status]=$"RC Run Level Settings" [fstab]=$"Fstab Settings"
+    [du]=$"Disk Usage & Statistics" [makeconf]=$"Settings from /etc/make.conf"
+    [portage]=$"General Portage Information" [profiles]=$"Display of Portage Profiles"
+    [kernel]=$"Kernel in use" [hardware]=$"PCI Hardware" [modules]=$"Kernel Modules Currently Loaded"
+    [udev]=$"UDEV Rules" [dbus]=$"DBUS Session Information" [consolekit]=$"Consolekit Session Information"
+    [username]=$"Username" [hostname]=$"Hostname"
+  # [yourModule]=$"Description"
+) # <- do not delete this bracket
 
-2>>"${out_tmp}" #redirect stderr to the file (like 'command not found')
+# ask user whether s/he wants to send this information via analyze_opt()
+analyze_opt_array=(
+    [exported]=$"Exported shell variables" [ifconfig]=$"Network status"
+    [route]=$"Routing Tables" [dns]=$"DNS Servers"
+  # [yourModule]=$"Description"
+) # <- do not delete
+
+# [description of] questions to put to user; text entered used as answer
+query_array=(
+    [wm]=$"Window Manager / Desktop Environment Information"
+  # [yourQuery]=$"Description"
+) # <- do not delete
+
+#######################################<<MODULE DATA>>##################################
+# format: data[module_identifier]='command to be executed' or $"question to be asked"
+declare -A data
+data=(
+    [rc_status]='rc-status' [fstab]='cat /etc/fstab' [du]='df -hT' [makeconf]='cat /etc/make.conf'
+    [portage]="emerge --info" [profiles]='eselect profile list' [kernel]='eselect kernel list'
+    [hardware]='lspci -k' [modules]='lsmod' [udev]='ls -1 /etc/udev/rules.d/'
+    [dbus]="echo $DBUS_SESSION_BUS_ADDRESS" [consolekit]='ck-list-sessions'
+    [username]="echo $USER" [hostname]="echo $HOSTNAME"
+    [exported]='export' [ifconfig]='ifconfig' [route]='route' [dns]='cat /etc/resolv.conf'
+    [wm]=$"what Desktop environment and/or Window manager are you using"
+  # [yourModule]='command -opts /some/path'
+  # [yourModule]="echo $variable. NB variables evaluated now, not when module called"
+  # [yourQuery]=$"question string"
+) # <- do not delete
+
+declare -i interactive=1 read_only=0
+declare -r EOL=$'\n' # newline so we can avoid echo -e
+
+# 2>>"$out_tmp" #redirect stderr to the file (like 'command not found')
+# the above doesn't change anything in context of the script
+# to do this you have to use exec tho i'd suggest > not >> at start of script, so:
+# exec 2>"$out_tmp" || { echo "Unable to open tmp file" >&2; exit 1; }
+# thing is we echo to stderr, so above isn't useful imo, unless we dup fds. [igli]
 
 ######################<< MODULE CLASSES (well, just bash functions,really) >>##############
 
 #this function takes two arguments: analyze(comment_on_the_module, command_to_generate_desired_output)
-function analyze 
-{
-    echo "############################## ${1} ##############################" >> "${out_tmp}"
-    echo -e "--->>>command executed: ${2}\n" >> "${out_tmp}"
-    $2 >> "${out_tmp}" 2>> "${out_tmp}"
-    echo -e "\n\n" >> "${out_tmp}"
-}
+analyze() {
+    echo "############################## $1 ##############################"
+    echo $"--->>>command executed: $2""$EOL"
+    $2 2>&1
+    echo "$EOL$EOL"
+} >> "$out_tmp"
 
 #this function takes arguments like (module), but asks if they should be run
-function analyze_opt 
-{
+analyze_opt() {
     while true ; do
-        read -p " << ${1} >> command to be run: \" ${2} \"   ANSWER: Y/n :  "
-        case ${REPLY} in
-            y|Y|"") 
-                echo "############################## ${1} ##############################" >> "${out_tmp}"
-                echo -e "--->>>command executed: ${2}\n" >> "${out_tmp}"
-                $2 >> "${out_tmp}" 2>>"${out_tmp}"
-                echo -e "\n\n" >> "${out_tmp}"
+        read -p $" << $1 >> command to be run: \" $2 \"   ANSWER: Y/n :  "
+        case $REPLY in
+            [yY]|'')
+            {   echo "############################## $1 ##############################"
+                echo $"--->>>command executed: $2""$EOL"
+                $2 2>&1
+                echo "$EOL$EOL"
+            } >> "$out_tmp"
                 break;;
-            n|N)
-                echo ">>> skipping module << ${1} >>"
+            [nN])
+                echo $"skipping module: << $1 >>"
                 break;;
             *)
-                echo ">>> didn't understand you, type 'y' or 'n'";;
+                echo $">>> didn't understand you, type 'y' or 'n'";;
         esac 
    done
 }
 
 #this function just asks the user about stuff, takes two arguments: query(module_name, the_question_to_the_user)
-function query
-{
-    read -p "PLEASE ANSWER (type,then press ENTER): ${2} ?  "
-    echo "############################## ${1} ##############################" >> "${out_tmp}"
-    echo -e "--->>> question asked: ${2}\n" >> "${out_tmp}"
-    echo $REPLY >> "${out_tmp}"
-    echo -e "\n\n" >> "${out_tmp}"
+query() {
+    read -p $"PLEASE ANSWER (type,then press ENTER): $2 ?  "
+    echo "############################## $1 ##############################" >> "$out_tmp"
+    echo $"--->>> question asked: $2""$EOL$EOL$REPLY$EOL$EOL" >> "$out_tmp"
 }
-    
-###############################<< MODULE DECLARATION >>################################
 
-# format: module_identifier=( "module description " "command to be executed/question to be asked") 
-# module_identifier: short, no whitespace (is used for referencing)
-# module description: capitalised, and no abbreviations please, should be understandable for everyone
-
-
-rc_status=( "RC Run Level Settings" "rc-status")
-fstab=("Fstab Settings" "cat /etc/fstab")
-du=("Disk Usage & Statistics" "df -hT")
-makeconf=("Settings from /etc/make.conf" "cat /etc/make.conf")
-portage=("General Portage Information" "emerge --info")
-profiles=("Display of Portage Profiles" "eselect profile list")
-kernel=("Kernel in use" "eselect kernel list")
-hardware=("PCI Hardware" "lspci -k")
-modules=("Modules Currently Loaded" "lsmod")
-udev=("UDEV Rules" "ls -1 /etc/udev/rules.d/")
-dbus=("DBUS-session Information" "echo ${DBUS_SESSION_BUS_ADDRESS}")
-consolekit=("Consolekit-session Information" "ck-list-sessions")
-wm=("Window Manager / Desktop Environment Information" "what Desktop environment and/or Window manager are you using")
-exported=("Exported shell variables" "export")
-username=("Username" "echo ${USER}")
-hostname=("Hostname" "echo ${HOSTNAME}")
-ifconfig=("Network status" "ifconfig")
-route=("Routing Tables" "route")
-dns=("DNS Servers" "cat /etc/resolv.conf")
-
-
-#######################################<<MODULE ARRAYS>>################################
-#format: class_array=( module_identifier_1 module_identifier_2 .. )
-analyze_array=(rc_status fstab du makeconf portage profiles kernel hardware modules udev dbus consolekit username hostname)
-analyze_opt_array=(exported ifconfig route dns)
-query_array=(wm)
-
+# check to make sure all modules listed in class arrays have a corresponding data item
+# we do this as user can omit modules, which we indicate by removing them from the data array
+sanityCheck() {
+    local n missing=()
+    for mod in "${!analyze_array[@]}" "${!analyze_opt_array[@]}" "${!query_array[@]}"; do
+        [[ ${data["$mod"]} ]] || missing+=("$mod")
+    done
+    n=${#missing[*]}
+    case $n in
+    0) return
+;;  1) echo $"! Module $missing is missing."
+;;  *) echo $"! $n modules missing: ${missing[*]}"
+;;  esac >&2
+    exit 2
+}
+sanityCheck
 
 ##########################<< COMMAND LINE OPTIONS PROCESSING >>#######################
 
-while [ $# -gt 0 ] ; do
+declare -A new_data
+omit=()
+declare -i bad_module=0
+while (($#)); do
     case $1 in
-        -h|--help)
-            echo "This bash script gathers information about your system and (optionally) uploads it"
-            echo "through wgetpaste. It is intended for support purposes on the #gentoo IRC support channel
-            "
-            echo "Usage: genalyze [options]
-            "
-            echo "Options:"
-            echo "-h, --help                            Display this message and exit"
-            echo "-n, --non-interactive                 Do not ask questions, assume default values, upload"
-            echo "-o, --omit <module_identifiers>       Do not execute specified modules"
-            echo "-w, --with-only <module_identifiers>  Execute explicitly only these modules"
-            echo "-r, --read-only                       Only display the file with information, don't upload"
-            echo "-l, --list                            List available modules and exit"
+        -[h?]|--help)
+            echo $"This bash script gathers information about your system and (optionally) uploads it
+through wgetpaste. It is intended for support purposes on the #gentoo IRC support channel""$EOL"
+
+            echo $"Usage: ${0##*/} [options]""$EOL"
+
+            echo $"Options:"
+            echo '-h, --help                            '$"Display this message and exit"
+            echo '-n, --non-interactive                 '$"Do not ask questions, assume default values, upload"
+            echo '-o, --omit '$"<module_identifiers>"'       '$"Do not execute specified modules"
+            echo '-w, --with-only '$"<module_identifiers>"'  '$"Execute explicitly only these modules"
+            echo '-r, --read-only                       '$"Only display the file with information, don't upload"
+            echo '-l, --list                            '$"List available modules and exit"
             exit 0;;
         -n|--non-interactive)
             interactive=0
@@ -116,94 +151,126 @@ while [ $# -gt 0 ] ; do
             query_array=()
             shift;;
         -d|--no-upload)
-            UPLOAD=0
+            upload=0
             shift;;
         -r|--read-only)
-            readonly=1
+            read_only=1
             shift;;
         -l|--list)
-            list_array=( ${analyze_array[@]} ${analyze_opt_array[@]} ${query_array[@]} )
-            echo -e "<module identifier> :: <module description> :: <command executed by module>"
-            for mod in ${list_array[@]} ; do
-                eval echo  ${mod} " :: " \${$mod[0]} " :: " \${$mod[1]} #TODO make a table layout
+            header() {
+                echo $"<module identifier> :: <module description> :: <$1>"
+            }
+            echo $"** Standard modules"
+            header $"command executed by module"
+            for mod in "${!analyze_array[@]}"; do
+                echo  "$mod  ::  ${analyze_array["$mod"]}  ::  ${data["$mod"]}"
             done
+            echo "$EOL"$"** User-confirmed modules"
+            header $"command executed by module"
+            for mod in "${!analyze_opt_array[@]}"; do
+                echo  "$mod  ::  ${analyze_opt_array["$mod"]}  ::  ${data["$mod"]}"
+            done
+            echo "$EOL"$"** General questions with text answer to upload"
+            header $"question asked by module"
+            for mod in "${!query_array[@]}"; do
+                echo  "$mod  ::  ${query_array["$mod"]}  ::  ${data["$mod"]}"
+            done
+            #TODO make a table layout
             exit 0;;
         -w|--with-only)
             shift
-            analyze_array=()
-            analyze_opt_array=()
-            query_array=()
-            until [[ $1 =~ -.* || $# -eq 0 ]] ; do
-                analyze_array=( ${analyze_array[@]} $1 )
+            until [[ $1 = -* || $# -eq 0 ]] ; do
+                if [[ ${data["$1"]} ]]; then
+                    new_data["$1"]=${data["$1"]}
+                else bad_module=1
+                    echo $"! Unknown module: $1" >&2
+                fi
                 shift
-            done;;
-        -o|--omit)
+            done
+;;      -o|--omit)
             shift
-            until [[ $1 =~ -.* || $# -eq 0 ]] ; do
-                analyze_array=${analyze_array#$1}
-                analyze_opt_array=${analyze_array#$1}
-                query_array=${analyze_array#$1}
+            until [[ $1 = -* || $# -eq 0 ]] ; do
+                if [[ ${data["$1"]} ]]; then
+                    omit+=("$1")
+                else bad_module=1
+                    echo $"! Unknown module: $1" >&2
+                fi
                 shift
             done;;
         *)
-            echo ">>> unknown option, try --help"
+            echo $">>> unknown option, try --help"
             exit 1;;
     esac
 done
 
+if ((bad_module)); then
+    echo $"** Known modules:""$EOL  ${!data[*]}$EOL**" >&2
+    exit 1
+fi
+
+if ((${#new_data[*]})); then
+    data=()
+    for mod in "${!new_data[@]}"; do
+        data["$mod"]=${new_data["$mod"]}
+    done
+fi
+
+if ((${#omit[*]})); then
+    for mod in "${omit[@]}"; do
+        unset "data[$mod]"
+    done
+fi
+unset new_data omit bad_module
+
 ##################################<<MODULE EXECUTION>>##############################3
 #loops over class arrays and executes functions
 
-echo ">>> Starting the genalyze script, collecting system information ..." 
+echo $">>> Starting the genalyze script, collecting system information ..." 
 
 #analyze()
-for mod in ${analyze_array[@]}; do
-    eval name=\${$mod[0]} 
-    eval command=\${$mod[1]}
-    analyze "${name}" "${command}"
+for mod in "${!analyze_array[@]}"; do
+    [[ ${data["$mod"]} ]] || continue
+    analyze "${analyze_array["$mod"]}" "${data["$mod"]}"
 done
 #analyze_opt()
-echo -e ">>> The following modules are optional. Answer [y]es if you would like to supply this information or [n]o if not.\n>>> You may just hit <ENTER> which defaults to answering 'yes'."
-for mod in ${analyze_opt_array[@]}; do
-    eval name=\${$mod[0]} 
-    eval command=\${$mod[1]}
-    analyze_opt "${name}" "${command}"
+echo $">>> The following modules are optional. Answer [y]es if you would like to supply this information or [n]o if not.$EOL>>> You may just hit <ENTER> which defaults to answering 'yes'."
+for mod in "${!analyze_opt_array[@]}"; do
+    [[ ${data["$mod"]} ]] || continue
+    analyze_opt "${analyze_opt_array["$mod"]}" "${data["$mod"]}"
 done
 #query()
-for mod in ${query_array[@]}; do
-    eval name=\${$mod[0]} 
-    eval command=\${$mod[1]}
-    query "${name}" "${command}"
+for mod in "${!query_array[@]}"; do
+    [[ ${data["$mod"]} ]] || continue
+    query "${query_array["$mod"]}" "${data["$mod"]}"
 done
 
 ########################<<ENDING SEQUENCE>>#############################
-echo ">>> your system info is at ${out_tmp}"
+echo $">>> your system info is at $out_tmp"
 
-if [ $interactive -eq 0 ] ; then
-    wgetpaste "${out_tmp}"
+if ((!interactive)); then
+    wgetpaste "$out_tmp"
     exit 0
-elif [ $readonly -eq 1 ] ; then
-    less "${out_tmp}"
+elif ((read_only)); then
+    less "$out_tmp"
 else
     while true ; do
-        read -n 1 -e -p ">>> What do you want to do now? 
+        read -n 1 -e -p $">>> What do you want to do now? 
         [u]pload system info file through wgetpaste
         [r]ead the file with 'less'
         [q]uit
         ANSWER: type 'u' or 'r' or 'q' :  "
         case $REPLY in
-            u)
-                wgetpaste "${out_tmp}";;
-            r)
-                less "${out_tmp}";;
-            q)
+            [uU])
+                wgetpaste "$out_tmp";;
+            [rR])
+                less "$out_tmp";;
+            [qQ])
                 break;;
             *)
-                echo "couldn't understand you, try again";;
+                echo $"couldn't understand you, try again";;
         esac
     done
 fi
 
-echo "    >>> Thank you for your cooperation :) <<<<   "
+echo $"    >>> Thank you for your cooperation :) <<<   "
 exit 0
-
